Explicitly convert the values to string
Since we read the value from YAML, we might get some weird stuff,
if we don't quote explicitly:

MacBook-Pro-van-Fokko:dbt-source fokkodriesprong$ python3
Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 26 2018, 19:50:54)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
>>>
>>> yaml.load("name: 19.25")
{'name': 19.25}
>>> data = yaml.load("name: 19.25")
>>> type(data['name'])
<class 'float'>

>>> data = yaml.load("name: 1925")
>>> type(data['name'])
<class 'int'>

>>> data = yaml.load("name: 'no'")
>>> type(data['name'])
<class 'str'>

>>> data = yaml.load("name: no")
>>> type(data['name'])
<class 'bool'>

This was the case when reading numerical table names:

2020-03-02 09:10:33,892358 (MainThread): Traceback (most recent call last):
  File "/usr/local/Cellar/dbt/0.15.2_1/libexec/lib/python3.7/site-packages/dbt/main.py", line 80, in main
    results, succeeded = handle_and_check(args)
  File "/usr/local/Cellar/dbt/0.15.2_1/libexec/lib/python3.7/site-packages/dbt/main.py", line 158, in handle_and_check
    task, res = run_from_args(parsed)
  File "/usr/local/Cellar/dbt/0.15.2_1/libexec/lib/python3.7/site-packages/dbt/main.py", line 210, in run_from_args
    results = task.run()
  File "/usr/local/Cellar/dbt/0.15.2_1/libexec/lib/python3.7/site-packages/dbt/task/generate.py", line 201, in run
    catalog_table = adapter.get_catalog(self.manifest)
  File "/usr/local/Cellar/dbt/0.15.2_1/libexec/lib/python3.7/site-packages/dbt/adapters/base/impl.py", line 1016, in get_catalog
    results = self._catalog_filter_table(table, manifest)
  File "/usr/local/Cellar/dbt/0.15.2_1/libexec/lib/python3.7/site-packages/dbt/adapters/bigquery/impl.py", line 493, in _catalog_filter_table
    return super()._catalog_filter_table(table, manifest)
  File "/usr/local/Cellar/dbt/0.15.2_1/libexec/lib/python3.7/site-packages/dbt/adapters/base/impl.py", line 998, in _catalog_filter_table
    return table.where(_catalog_filter_schemas(manifest))
  File "/usr/local/Cellar/dbt/0.15.2_1/libexec/lib/python3.7/site-packages/agate/table/where.py", line 25, in where
    if test(row):
  File "/usr/local/Cellar/dbt/0.15.2_1/libexec/lib/python3.7/site-packages/dbt/adapters/base/impl.py", line 82, in test
    return (table_database.lower(), table_schema.lower()) in schemas
AttributeError: 'decimal.Decimal' object has no attribute 'lower'